/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LocalBank } from "./LocalBank";
export type { NationalBank } from "./NationalBank";
export type { WorldBankReserve } from "./WorldBankReserve";
