/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WorldBankReserveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "GOVERNOR_ROLE"
      | "NATIONAL_BANK_ROLE"
      | "allocate"
      | "deposit"
      | "emergencyWithdraw"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "lendingAprBps"
      | "listNationalBanks"
      | "nationalBanks"
      | "pause"
      | "paused"
      | "recordRepayment"
      | "registerNationalBank"
      | "renounceRole"
      | "reserveBalance"
      | "revokeNationalBank"
      | "revokeRole"
      | "setLendingApr"
      | "supportsInterface"
      | "systemStats"
      | "totalAllocated"
      | "totalDeposits"
      | "totalRepaid"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CapitalAllocated"
      | "DepositReceived"
      | "EmergencyWithdrawal"
      | "LendingAprUpdated"
      | "NationalBankRegistered"
      | "NationalBankRevoked"
      | "Paused"
      | "RepaymentRecorded"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GOVERNOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NATIONAL_BANK_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocate",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lendingAprBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listNationalBanks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nationalBanks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordRepayment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerNationalBank",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeNationalBank",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingApr",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "systemStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalAllocated",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRepaid",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GOVERNOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NATIONAL_BANK_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allocate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lendingAprBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listNationalBanks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nationalBanks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordRepayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNationalBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeNationalBank",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLendingApr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalAllocated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRepaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace CapitalAllocatedEvent {
  export type InputTuple = [bank: AddressLike, amount: BigNumberish];
  export type OutputTuple = [bank: string, amount: bigint];
  export interface OutputObject {
    bank: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositReceivedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawalEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LendingAprUpdatedEvent {
  export type InputTuple = [oldBps: BigNumberish, newBps: BigNumberish];
  export type OutputTuple = [oldBps: bigint, newBps: bigint];
  export interface OutputObject {
    oldBps: bigint;
    newBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NationalBankRegisteredEvent {
  export type InputTuple = [
    bank: AddressLike,
    name: string,
    jurisdiction: string
  ];
  export type OutputTuple = [bank: string, name: string, jurisdiction: string];
  export interface OutputObject {
    bank: string;
    name: string;
    jurisdiction: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NationalBankRevokedEvent {
  export type InputTuple = [bank: AddressLike];
  export type OutputTuple = [bank: string];
  export interface OutputObject {
    bank: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepaymentRecordedEvent {
  export type InputTuple = [
    bank: AddressLike,
    principal: BigNumberish,
    interest: BigNumberish
  ];
  export type OutputTuple = [bank: string, principal: bigint, interest: bigint];
  export interface OutputObject {
    bank: string;
    principal: bigint;
    interest: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldBankReserve extends BaseContract {
  connect(runner?: ContractRunner | null): WorldBankReserve;
  waitForDeployment(): Promise<this>;

  interface: WorldBankReserveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  GOVERNOR_ROLE: TypedContractMethod<[], [string], "view">;

  NATIONAL_BANK_ROLE: TypedContractMethod<[], [string], "view">;

  allocate: TypedContractMethod<
    [bank: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<[], [void], "payable">;

  emergencyWithdraw: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  lendingAprBps: TypedContractMethod<[], [bigint], "view">;

  listNationalBanks: TypedContractMethod<[], [string[]], "view">;

  nationalBanks: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string, bigint, bigint, bigint] & {
        registered: boolean;
        name: string;
        jurisdiction: string;
        allocated: bigint;
        outstanding: bigint;
        repaid: bigint;
      }
    ],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recordRepayment: TypedContractMethod<
    [principal: BigNumberish],
    [void],
    "payable"
  >;

  registerNationalBank: TypedContractMethod<
    [bank: AddressLike, name: string, jurisdiction: string],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  reserveBalance: TypedContractMethod<[], [bigint], "view">;

  revokeNationalBank: TypedContractMethod<
    [bank: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setLendingApr: TypedContractMethod<
    [newBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  systemStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        balance: bigint;
        deposits: bigint;
        allocated: bigint;
        repaid: bigint;
        bankCount: bigint;
      }
    ],
    "view"
  >;

  totalAllocated: TypedContractMethod<[], [bigint], "view">;

  totalDeposits: TypedContractMethod<[], [bigint], "view">;

  totalRepaid: TypedContractMethod<[], [bigint], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GOVERNOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "NATIONAL_BANK_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "allocate"
  ): TypedContractMethod<
    [bank: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "lendingAprBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listNationalBanks"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "nationalBanks"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, string, string, bigint, bigint, bigint] & {
        registered: boolean;
        name: string;
        jurisdiction: string;
        allocated: bigint;
        outstanding: bigint;
        repaid: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recordRepayment"
  ): TypedContractMethod<[principal: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "registerNationalBank"
  ): TypedContractMethod<
    [bank: AddressLike, name: string, jurisdiction: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reserveBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeNationalBank"
  ): TypedContractMethod<[bank: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLendingApr"
  ): TypedContractMethod<[newBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "systemStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        balance: bigint;
        deposits: bigint;
        allocated: bigint;
        repaid: bigint;
        bankCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalAllocated"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDeposits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRepaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "CapitalAllocated"
  ): TypedContractEvent<
    CapitalAllocatedEvent.InputTuple,
    CapitalAllocatedEvent.OutputTuple,
    CapitalAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositReceived"
  ): TypedContractEvent<
    DepositReceivedEvent.InputTuple,
    DepositReceivedEvent.OutputTuple,
    DepositReceivedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawal"
  ): TypedContractEvent<
    EmergencyWithdrawalEvent.InputTuple,
    EmergencyWithdrawalEvent.OutputTuple,
    EmergencyWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "LendingAprUpdated"
  ): TypedContractEvent<
    LendingAprUpdatedEvent.InputTuple,
    LendingAprUpdatedEvent.OutputTuple,
    LendingAprUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NationalBankRegistered"
  ): TypedContractEvent<
    NationalBankRegisteredEvent.InputTuple,
    NationalBankRegisteredEvent.OutputTuple,
    NationalBankRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NationalBankRevoked"
  ): TypedContractEvent<
    NationalBankRevokedEvent.InputTuple,
    NationalBankRevokedEvent.OutputTuple,
    NationalBankRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RepaymentRecorded"
  ): TypedContractEvent<
    RepaymentRecordedEvent.InputTuple,
    RepaymentRecordedEvent.OutputTuple,
    RepaymentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "CapitalAllocated(address,uint256)": TypedContractEvent<
      CapitalAllocatedEvent.InputTuple,
      CapitalAllocatedEvent.OutputTuple,
      CapitalAllocatedEvent.OutputObject
    >;
    CapitalAllocated: TypedContractEvent<
      CapitalAllocatedEvent.InputTuple,
      CapitalAllocatedEvent.OutputTuple,
      CapitalAllocatedEvent.OutputObject
    >;

    "DepositReceived(address,uint256)": TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;
    DepositReceived: TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;

    "EmergencyWithdrawal(address,uint256)": TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;
    EmergencyWithdrawal: TypedContractEvent<
      EmergencyWithdrawalEvent.InputTuple,
      EmergencyWithdrawalEvent.OutputTuple,
      EmergencyWithdrawalEvent.OutputObject
    >;

    "LendingAprUpdated(uint256,uint256)": TypedContractEvent<
      LendingAprUpdatedEvent.InputTuple,
      LendingAprUpdatedEvent.OutputTuple,
      LendingAprUpdatedEvent.OutputObject
    >;
    LendingAprUpdated: TypedContractEvent<
      LendingAprUpdatedEvent.InputTuple,
      LendingAprUpdatedEvent.OutputTuple,
      LendingAprUpdatedEvent.OutputObject
    >;

    "NationalBankRegistered(address,string,string)": TypedContractEvent<
      NationalBankRegisteredEvent.InputTuple,
      NationalBankRegisteredEvent.OutputTuple,
      NationalBankRegisteredEvent.OutputObject
    >;
    NationalBankRegistered: TypedContractEvent<
      NationalBankRegisteredEvent.InputTuple,
      NationalBankRegisteredEvent.OutputTuple,
      NationalBankRegisteredEvent.OutputObject
    >;

    "NationalBankRevoked(address)": TypedContractEvent<
      NationalBankRevokedEvent.InputTuple,
      NationalBankRevokedEvent.OutputTuple,
      NationalBankRevokedEvent.OutputObject
    >;
    NationalBankRevoked: TypedContractEvent<
      NationalBankRevokedEvent.InputTuple,
      NationalBankRevokedEvent.OutputTuple,
      NationalBankRevokedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RepaymentRecorded(address,uint256,uint256)": TypedContractEvent<
      RepaymentRecordedEvent.InputTuple,
      RepaymentRecordedEvent.OutputTuple,
      RepaymentRecordedEvent.OutputObject
    >;
    RepaymentRecorded: TypedContractEvent<
      RepaymentRecordedEvent.InputTuple,
      RepaymentRecordedEvent.OutputTuple,
      RepaymentRecordedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
