/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace WorldBankReserve {
  export type LoanStruct = {
    id: BigNumberish;
    borrower: AddressLike;
    amount: BigNumberish;
    purpose: string;
    status: BigNumberish;
    requestedAt: BigNumberish;
    approvedAt: BigNumberish;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrower: string,
    amount: bigint,
    purpose: string,
    status: bigint,
    requestedAt: bigint,
    approvedAt: bigint
  ] & {
    id: bigint;
    borrower: string;
    amount: bigint;
    purpose: string;
    status: bigint;
    requestedAt: bigint;
    approvedAt: bigint;
  };
}

export interface WorldBankReserveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveLoan"
      | "depositToReserve"
      | "emergencyWithdraw"
      | "getLoan"
      | "getPendingLoans"
      | "getStats"
      | "getTotalReserve"
      | "getUserDeposits"
      | "getUserLoans"
      | "loanCounter"
      | "loans"
      | "owner"
      | "pause"
      | "paused"
      | "rejectLoan"
      | "renounceOwnership"
      | "requestLoan"
      | "totalReserve"
      | "transferOwnership"
      | "unpause"
      | "userDeposits"
      | "userLoans"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoanApproved"
      | "LoanRejected"
      | "LoanRequested"
      | "OwnershipTransferred"
      | "ReserveDeposited"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingLoans",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getTotalReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserDeposits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "loanCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReserve",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userDeposits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLoans",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rejectLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userLoans", data: BytesLike): Result;
}

export namespace LoanApprovedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [loanId: bigint, borrower: string, amount: bigint];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRejectedEvent {
  export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [loanId: bigint, borrower: string];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    purpose: string
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    amount: bigint,
    purpose: string
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
    purpose: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveDepositedEvent {
  export type InputTuple = [
    depositor: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    depositor: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WorldBankReserve extends BaseContract {
  connect(runner?: ContractRunner | null): WorldBankReserve;
  waitForDeployment(): Promise<this>;

  interface: WorldBankReserveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositToReserve: TypedContractMethod<[], [void], "payable">;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  getLoan: TypedContractMethod<
    [loanId: BigNumberish],
    [WorldBankReserve.LoanStructOutput],
    "view"
  >;

  getPendingLoans: TypedContractMethod<
    [],
    [WorldBankReserve.LoanStructOutput[]],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalReserve: bigint;
        _totalLoans: bigint;
        _pendingLoans: bigint;
        _approvedLoans: bigint;
      }
    ],
    "view"
  >;

  getTotalReserve: TypedContractMethod<[], [bigint], "view">;

  getUserDeposits: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getUserLoans: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  loanCounter: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        borrower: string;
        amount: bigint;
        purpose: string;
        status: bigint;
        requestedAt: bigint;
        approvedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  rejectLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestLoan: TypedContractMethod<
    [amount: BigNumberish, purpose: string],
    [void],
    "nonpayable"
  >;

  totalReserve: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userDeposits: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositToReserve"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: BigNumberish],
    [WorldBankReserve.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingLoans"
  ): TypedContractMethod<[], [WorldBankReserve.LoanStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        _totalReserve: bigint;
        _totalLoans: bigint;
        _pendingLoans: bigint;
        _approvedLoans: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserDeposits"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserLoans"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "loanCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, bigint, bigint, bigint] & {
        id: bigint;
        borrower: string;
        amount: bigint;
        purpose: string;
        status: bigint;
        requestedAt: bigint;
        approvedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rejectLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<
    [amount: BigNumberish, purpose: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalReserve"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userDeposits"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "LoanApproved"
  ): TypedContractEvent<
    LoanApprovedEvent.InputTuple,
    LoanApprovedEvent.OutputTuple,
    LoanApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRejected"
  ): TypedContractEvent<
    LoanRejectedEvent.InputTuple,
    LoanRejectedEvent.OutputTuple,
    LoanRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveDeposited"
  ): TypedContractEvent<
    ReserveDepositedEvent.InputTuple,
    ReserveDepositedEvent.OutputTuple,
    ReserveDepositedEvent.OutputObject
  >;

  filters: {
    "LoanApproved(uint256,address,uint256)": TypedContractEvent<
      LoanApprovedEvent.InputTuple,
      LoanApprovedEvent.OutputTuple,
      LoanApprovedEvent.OutputObject
    >;
    LoanApproved: TypedContractEvent<
      LoanApprovedEvent.InputTuple,
      LoanApprovedEvent.OutputTuple,
      LoanApprovedEvent.OutputObject
    >;

    "LoanRejected(uint256,address)": TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;
    LoanRejected: TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;

    "LoanRequested(uint256,address,uint256,string)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReserveDeposited(address,uint256,uint256)": TypedContractEvent<
      ReserveDepositedEvent.InputTuple,
      ReserveDepositedEvent.OutputTuple,
      ReserveDepositedEvent.OutputObject
    >;
    ReserveDeposited: TypedContractEvent<
      ReserveDepositedEvent.InputTuple,
      ReserveDepositedEvent.OutputTuple,
      ReserveDepositedEvent.OutputObject
    >;
  };
}
