/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LocalBank__factory } from "./LocalBank__factory";
export { NationalBank__factory } from "./NationalBank__factory";
export { WorldBankReserve__factory } from "./WorldBankReserve__factory";
